export type Zones =
  | 'Argentina'
  | 'Brazil'
  | 'Peru'
  | 'Venezuela'
  | 'Central America'
  | 'Western US'
  | 'Eastern US'
  | 'Alberta'
  | 'Alaska'
  | 'Northwest Territory'
  | 'Ontario'
  | 'Quebec'
  | 'Greenland'
  | 'Iceland'
  | 'Great Britain'
  | 'Western Europe'
  | 'Southern Europe'
  | 'Northern Europe'
  | 'Scandinavia'
  | 'Ukraine'
  | 'North Africa'
  | 'Egypt'
  | 'East Africa'
  | 'Congo'
  | 'Madagascar'
  | 'South Africa'
  | 'Middle East'
  | 'Afghanistan'
  | 'India'
  | 'Ural'
  | 'Siberia'
  | 'Yakutsk'
  | 'Kamchatka'
  | 'Irkutsk'
  | 'Mongolia'
  | 'Japan'
  | 'China'
  | 'Siam'
  | 'Indonesia'
  | 'New Guinea'
  | 'Western Australia'
  | 'Eastern Australia';

export type Continents =
  | 'North America'
  | 'South America'
  | 'Africa'
  | 'Europe'
  | 'Australia'
  | 'Asia';
